### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by athiessen64** [aronwoost/google-calendar-hours#127]
2 issues I've found recently. 

1. When I try to run a range of days, I have to select the day before and the day after the actual days that I want. For example, if I want the 1st-15th of the month, I have to select the last day of the previous month and the 16th, in order to have the 1st and 15th included. If I select from the 1st to the 15th, I only get results for the 2nd to the 14th.

2. The export to csv used to give me the date and the correct times in my time zone (mountain time), but now the export shows the times 6 hours ahead of the actual times in the events and the formatting is messed up, there's the date, then a T, then the time with 3 zeros and a Z after so I have to reformat the entire cell in order to get what I want which is the date and the correct time.

**Comment by aronwoost** [comment]
1. Have you experienced this last week or just now? Because I applied a fix regarding the date picker some days ago. Maybe it's already fixed be that.
2. I just introduced that new time format that should solve the timezone issue once and for all. It includes the timezone and your software should apply the timezone difference automatically. **SHOULD!** Because a quick search reveals that neither Google Sheets not Excel are actually able to parse it. 🤦‍♀️🤦‍♀️🤦‍♀️ I'll revert the change.

**Comment by aronwoost** [comment]
2. should be fixed. 🧹

**Comment by athiessen64** [comment]
1. I experienced the issue with the date picker about a week ago.  I just tried it again and I still have to pick a date after the date I want in order to get the date I want.

2. Thanks so much for fixing the time format. This was my bigger issue of the 2 and now that you've fixed it, it's saved me a ton of work. Much appreciated

**Comment by aronwoost** [comment]
I see now that the end date is not included in the calculation when using a custom range. I'm working on a fix (some stuff needs to be reworked 💪).

**Comment by aronwoost** [comment]
1. should also be fixed. Pls verify.

**Comment by athiessen64** [comment]
Confirmed, the custom date range is working. Thanks again for fixing both issues, hope you have a great weekend.

**Comment by aronwoost** [comment]
🍭
